# Generated by Django 3.2.20 on 2023-11-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='color',
            field=models.CharField(choices=[('darkred', 'Dunkelrot'), ('red', 'Rot'), ('darkorange', 'Dunkelorange'), ('orange', 'Orange'), ('lightgreen', 'Hellgrün'), ('darkgreen', 'Dunkelgrün'), ('darkcyan', 'Türkis'), ('lightblue', 'Hellblau'), ('darkblue', 'Dunkelblau'), ('mediumpurple', 'Violett'), ('hotpink', 'Rosa'), ('gray', 'Grau'), ('brown', 'Braun'), ('black', 'Schwarz')], default='black', max_length=20, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
    ]
