# Generated by Django 4.2.4 on 2023-08-16 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomPermisison',
            new_name='CustomPermissison',
        ),
    ]
