# Generated by Django 4.2.4 on 2023-08-16 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_rename_custompermisison_custompermissison'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompermissison',
            name='description',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
