# Generated by Django 4.2.4 on 2023-08-16 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_rename_custompermissison_custompermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='color',
            field=models.CharField(choices=[('Rot', 'red'), ('Orange', 'orange'), ('Gelb', 'yellow'), ('Hellgrün', 'lime'), ('Grün', 'green'), ('Türkis', 'cyan'), ('Blau', 'blue'), ('Violett', 'purple'), ('Rosa', 'pink'), ('Grau', 'gray'), ('Braun', 'brown'), ('Schwarz', 'black')], default='Schwarz', max_length=20),
        ),
    ]
