# Generated by Django 4.2.4 on 2023-08-16 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_alter_role_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='color',
            field=models.CharField(choices=[('red', 'red'), ('orange', 'orange'), ('yellow', 'yellow'), ('lime', 'lime'), ('green', 'green'), ('darkgreen', 'darkgreen'), ('cyan', 'cyan'), ('blue', 'blue'), ('purple', 'purple'), ('pink', 'pink'), ('gray', 'gray'), ('brown', 'brown'), ('black', 'black')], default='black', max_length=20),
        ),
    ]
