# Generated by Django 4.2.4 on 2023-08-16 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_alter_role_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='color',
            field=models.CharField(choices=[('darkred', 'Rot'), ('red', 'red'), ('darkorange', 'darkorange'), ('orange', 'orange'), ('lightgreen', 'lightgreen'), ('darkgreen', 'darkgreen'), ('darkcyan', 'darkcyan'), ('lightblue', 'lightblue'), ('darkblue', 'darkblue'), ('mediumpurple', 'mediumpurple'), ('hotpink', 'hotpink'), ('gray', 'gray'), ('brown', 'brown'), ('black', 'black')], default='black', max_length=20),
        ),
    ]
