# Generated by Django 4.2.4 on 2023-09-17 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='name',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='capacity',
            field=models.CharField(default=1, max_length=20, verbose_name='Lagerkapazität'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='condition',
            field=models.CharField(choices=[('passenger_car', 'Personenwagen'), ('van', 'Kleintransporter'), ('delivery_truck', 'Lastwagen'), ('dump_truck', 'Kipplaster'), ('tanker_truck', 'Tanklastwagen'), ('tow_truck', 'Abschleppwagen'), ('pump_truck', 'Betonpumpenwagen'), ('explosive_truck', 'Sprengstofflastwagen'), ('garbage_truck', 'Müllsammellastwagen')], default='unused', max_length=20, verbose_name='Zustand'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_consumption',
            field=models.CharField(default=1, max_length=20, verbose_name='Durchschnittlicher Kraftstoffverbrauch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('passenger_car', 'Personenwagen'), ('van', 'Kleintransporter'), ('delivery_truck', 'Lastwagen'), ('dump_truck', 'Kipplaster'), ('tanker_truck', 'Tanklastwagen'), ('tow_truck', 'Abschleppwagen'), ('pump_truck', 'Betonpumpenwagen'), ('explosive_truck', 'Sprengstofflastwagen'), ('garbage_truck', 'Müllsammellastwagen')], default='diesel', max_length=20, verbose_name='Fahrzeugtyp'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance',
            field=models.TextField(blank=True, default='Keine Angaben', max_length=200, null=True, verbose_name='Versicherungsdaten'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(default=1, max_length=20, verbose_name='Kennzeichen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='manufacturer',
            field=models.CharField(default=1, max_length=20, verbose_name='Hersteller'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.CharField(default=1, max_length=20, verbose_name='Fahrzeugmodell'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='power_engine',
            field=models.CharField(blank=True, default='Unbekannt', max_length=20, null=True, verbose_name='Leistung & Motor'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('passenger_car', 'Personenwagen'), ('van', 'Kleintransporter'), ('delivery_truck', 'Lastwagen'), ('dump_truck', 'Kipplaster'), ('tanker_truck', 'Tanklastwagen'), ('tow_truck', 'Abschleppwagen'), ('pump_truck', 'Betonpumpenwagen'), ('explosive_truck', 'Sprengstofflastwagen'), ('garbage_truck', 'Müllsammellastwagen')], default='passenger_car', max_length=20, verbose_name='Fahrzeugtyp'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(default=1, max_length=20, verbose_name='Identifikationsnummer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='year_of_manufacturer',
            field=models.CharField(default=1, max_length=20, verbose_name='Baujahr'),
            preserve_default=False,
        ),
    ]
