# Generated by Django 4.2.4 on 2023-09-17 01:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposition', '0002_remove_vehicle_name_vehicle_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='year_of_manufacturer',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900)], verbose_name='Baujahr'),
        ),
    ]
