# Generated by Django 4.2.4 on 2023-09-17 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposition', '0003_alter_vehicle_year_of_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='name',
            field=models.CharField(blank=True, default='Keine', max_length=20, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(max_length=20, verbose_name='Kennzeichen*'),
        ),
    ]
