# Generated by Django 4.2.4 on 2023-09-17 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposition', '0004_vehicle_name_alter_vehicle_license_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(max_length=20, verbose_name='Kennzeichen *'),
        ),
    ]
