# Generated by Django 4.2.4 on 2023-09-17 01:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposition', '0006_alter_vehicle_capacity_alter_vehicle_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='year_of_manufacturer',
            field=models.PositiveIntegerField(default=1900, validators=[django.core.validators.MinValueValidator(1900)], verbose_name='Baujahr*'),
        ),
    ]
