# Generated by Django 4.2.4 on 2023-09-17 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disposition', '0007_alter_vehicle_year_of_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='condition',
        ),
    ]
