# Generated by Django 4.2.4 on 2023-09-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposition', '0008_remove_vehicle_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='condition',
            field=models.CharField(choices=[('unused', 'Nicht gebraucht'), ('used', 'Gebraucht'), ('damaged', 'Beschädigt'), ('repaired', 'Repariert'), ('total_loss', 'Totalschaden'), ('needs_maintenance', 'Instandhaltungsbedarf'), ('not_drivable', 'Nicht Fahrbereit'), ('modified', 'Modifiziert')], default='unused', max_length=20, verbose_name='Zustand*'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('diesel', 'Diesel'), ('gasoline', 'Benzin'), ('electric', 'Elektrisch'), ('hydrogen', 'Wasserstoff'), ('natural_gas', 'Erdgas'), ('biodiesel', 'Biodiesel'), ('lpg', 'Autogas'), ('e85', 'E85'), ('lng', 'Flüssigerdgas')], default='diesel', max_length=20, verbose_name='Fahrzeugtyp*'),
        ),
    ]
