# Generated by Django 4.2.4 on 2023-09-17 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposition', '0009_vehicle_condition_alter_vehicle_fuel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('passenger_car', 'Personenwagen'), ('van', 'Kleintransporter'), ('delivery_truck', 'Lieferwagen'), ('truck', 'Lastwagen'), ('dump_truck', 'Kipplaster'), ('tanker_truck', 'Tanklastwagen'), ('tow_truck', 'Abschleppwagen'), ('pump_truck', 'Betonpumpenwagen'), ('explosive_truck', 'Sprengstofflastwagen'), ('garbage_truck', 'Müllsammellastwagen')], default='passenger_car', max_length=20, verbose_name='Fahrzeugtyp*'),
        ),
    ]
