# Generated by Django 4.2.4 on 2023-09-17 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposition', '0010_alter_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('passenger_car', 'Personenwagen'), ('van', 'Kleintransporter'), ('truck', 'Lastwagen'), ('delivery_truck', 'Lieferwagen'), ('cargo_container_truck', 'Frachtcontainerlastwagen'), ('dump_truck', 'Kipplaster'), ('tanker_truck', 'Tanklastwagen'), ('tow_truck', 'Abschleppwagen'), ('truck_flatbed', 'Pritschenwagen'), ('trailer', 'Anhänger')], default='passenger_car', max_length=50, verbose_name='Fahrzeugtyp*'),
        ),
    ]
