# Generated by Django 3.2.20 on 2023-11-04 05:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposition', '0013_alter_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='capacity',
            field=models.CharField(max_length=20, verbose_name='Storage Capacity*'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='condition',
            field=models.CharField(choices=[('unused', 'Nicht gebraucht'), ('used', 'Gebraucht'), ('damaged', 'Beschädigt'), ('repaired', 'Repariert'), ('total_loss', 'Totalschaden'), ('needs_maintenance', 'Instandhaltungsbedarf'), ('not_drivable', 'Nicht Fahrbereit'), ('modified', 'Modifiziert')], default='unused', max_length=20, verbose_name='Condition*'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_consumption',
            field=models.CharField(max_length=20, verbose_name='Average Fuel Consumption*'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('diesel', 'Diesel'), ('gasoline', 'Benzin'), ('electric', 'Elektrisch'), ('hydrogen', 'Wasserstoff'), ('natural_gas', 'Erdgas'), ('biodiesel', 'Biodiesel'), ('lpg', 'Autogas'), ('e85', 'E85'), ('lng', 'Flüssigerdgas')], default='diesel', max_length=20, verbose_name='Fuel Type*'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(max_length=20, verbose_name='License Plate*'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='manufacturer',
            field=models.CharField(max_length=20, verbose_name='Manufacturer*'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=20, verbose_name='Vehicle Model*'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('passenger_car', 'Personenwagen'), ('van', 'Kleintransporter'), ('truck', 'Lastwagen'), ('delivery_truck', 'Lieferwagen'), ('cargo_container_truck', 'Frachtcontainerlastwagen'), ('dump_truck', 'Kipplaster'), ('tanker_truck', 'Tanklastwagen'), ('tow_truck', 'Abschleppwagen'), ('flatbed_truck', 'Pritschenwagen'), ('trailer_truck', 'Anhänger')], default='passenger_car', max_length=50, verbose_name='Vehicle Type*'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(max_length=20, verbose_name='Identification Number*'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year_of_manufacturer',
            field=models.PositiveIntegerField(default=1900, validators=[django.core.validators.MinValueValidator(1900)], verbose_name='Year of Manufacture*'),
        ),
    ]
