# Generated by Django 3.2.20 on 2024-02-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposition', '0014_auto_20231104_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='capacity',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Kapazität'),
        ),
        migrations.AlterField(
            model_name='station',
            name='contactmail',
            field=models.EmailField(blank=True, max_length=30, null=True, verbose_name='Kontakt E-Mail'),
        ),
        migrations.AlterField(
            model_name='station',
            name='contactphone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Kontakt Mobile'),
        ),
        migrations.AlterField(
            model_name='station',
            name='country',
            field=models.CharField(max_length=30, verbose_name='Land'),
        ),
        migrations.AlterField(
            model_name='station',
            name='location',
            field=models.CharField(max_length=30, verbose_name='Ort'),
        ),
        migrations.AlterField(
            model_name='station',
            name='state',
            field=models.CharField(max_length=30, verbose_name='Bundesland / Kanton'),
        ),
        migrations.AlterField(
            model_name='station',
            name='street',
            field=models.CharField(max_length=30, verbose_name='Strasse'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='capacity',
            field=models.CharField(max_length=20, verbose_name='Lagerkapazität'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='condition',
            field=models.CharField(choices=[('unused', 'Nicht gebraucht'), ('used', 'Gebraucht'), ('damaged', 'Beschädigt'), ('repaired', 'Repariert'), ('total_loss', 'Totalschaden'), ('needs_maintenance', 'Instandhaltungsbedarf'), ('not_drivable', 'Nicht Fahrbereit'), ('modified', 'Modifiziert')], default='unused', max_length=20, verbose_name='Zustand'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_consumption',
            field=models.CharField(max_length=20, verbose_name='Durchschnittlicher Kraftstoffverbrauch'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('diesel', 'Diesel'), ('gasoline', 'Benzin'), ('electric', 'Elektrisch'), ('hydrogen', 'Wasserstoff'), ('natural_gas', 'Erdgas'), ('biodiesel', 'Biodiesel'), ('lpg', 'Autogas'), ('e85', 'E85'), ('lng', 'Flüssigerdgas')], default='diesel', max_length=20, verbose_name='Kraftstofftyp'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(max_length=20, verbose_name='Kennzeichen'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='manufacturer',
            field=models.CharField(max_length=20, verbose_name='Hersteller'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=20, verbose_name='Fahrzeugmodell'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('passenger_car', 'Personenwagen'), ('van', 'Kleintransporter'), ('truck', 'Lastwagen'), ('delivery_truck', 'Lieferwagen'), ('cargo_container_truck', 'Frachtcontainerlastwagen'), ('dump_truck', 'Kipplaster'), ('tanker_truck', 'Tanklastwagen'), ('tow_truck', 'Abschleppwagen'), ('flatbed_truck', 'Pritschenwagen'), ('trailer_truck', 'Anhänger')], default='passenger_car', max_length=50, verbose_name='Fahrzeugtyp'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(max_length=20, verbose_name='Identifikationsnummer'),
        ),
    ]
