# Generated by Django 3.2.20 on 2024-02-10 22:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposition', '0015_auto_20240210_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='year_of_manufacturer',
            field=models.PositiveIntegerField(default=1900, validators=[django.core.validators.MinValueValidator(1900)], verbose_name='Baujahr'),
        ),
    ]
