# Generated by Django 3.2.20 on 2024-02-10 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposition', '0016_alter_vehicle_year_of_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='contactmail',
            field=models.EmailField(blank=True, max_length=30, null=True, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='station',
            name='contactphone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='station',
            name='state',
            field=models.CharField(max_length=30, verbose_name='Bundesland'),
        ),
    ]
