# Generated by Django 3.2.20 on 2023-10-29 22:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='receiver',
        ),
        migrations.AddField(
            model_name='announcement',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver_read',
            field=models.BooleanField(default=False),
        ),
    ]
