# Generated by Django 3.2.20 on 2023-11-06 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0009_rename_corpotion_signature_corporation'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='zip',
            field=models.IntegerField(blank=True, null=True, verbose_name='PLZ'),
        ),
    ]
