# Generated by Django 3.2.20 on 2023-11-06 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0010_signature_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='zip',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='PLZ'),
        ),
    ]
