# Generated by Django 3.2.20 on 2023-11-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0012_signature_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='show_Location',
            field=models.BooleanField(default=True, verbose_name='Ort anzeigen'),
        ),
        migrations.AddField(
            model_name='signature',
            name='show_corporation',
            field=models.BooleanField(default=True, verbose_name='Unternehmen anzeigen'),
        ),
        migrations.AddField(
            model_name='signature',
            name='show_country',
            field=models.BooleanField(default=True, verbose_name='Land anzeigen'),
        ),
        migrations.AddField(
            model_name='signature',
            name='show_housenumber',
            field=models.BooleanField(default=True, verbose_name='Hausnummer anzeigen'),
        ),
        migrations.AddField(
            model_name='signature',
            name='show_logo',
            field=models.BooleanField(default=True, verbose_name='Logo anzeigen'),
        ),
        migrations.AddField(
            model_name='signature',
            name='show_name',
            field=models.BooleanField(default=True, verbose_name='Name anzeigen'),
        ),
        migrations.AddField(
            model_name='signature',
            name='show_role',
            field=models.BooleanField(default=True, verbose_name='Rollen anzeigen'),
        ),
        migrations.AddField(
            model_name='signature',
            name='show_url',
            field=models.BooleanField(default=True, verbose_name='Webseite anzeigen'),
        ),
        migrations.AddField(
            model_name='signature',
            name='show_zip',
            field=models.BooleanField(default=True, verbose_name='PLZ anzeigen'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ort'),
        ),
    ]
