# Generated by Django 4.2.4 on 2023-12-25 03:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0002_auto_20231104_0538'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(blank=True, default='OfficeSync', max_length=20, null=True)),
                ('logo', models.ImageField(blank=True, default='authentication/static/images/uploads/logo_default/officesync.png', null=True, upload_to='authentication/static/images/uploads/logo')),
            ],
        ),
        migrations.CreateModel(
            name='Warn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('misinformation', 'Falschinformationen'), ('abuse', 'Missbrauch von Privilegien'), ('harassment', 'Belästigung'), ('bullying', 'Cybermobbing'), ('grooming', 'Cybergrooming'), ('whataboutism', 'Whataboutismus'), ('relativisation', 'Relativierung'), ('blackmailing', 'Erpressung'), ('threat', 'Drohung'), ('cow', 'Wortwahl'), ('hatespeech', 'Hassrede'), ('swearword', 'Beleidigung'), ('discrimination', 'Diskriminierung'), ('Sexism', 'Sexismus'), ('racism', 'Rassismus'), ('fascism', 'Faschismus'), ('antisemitism', 'Antisemitismus'), ('islamophobia', 'Islamophobie'), ('homophobia', 'Homophobie'), ('scam', 'Betrug'), ('spam', 'Spam')], default='hatespeech', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCustomInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ui', models.CharField(choices=[('light', 'Hell'), ('dark', 'Dunkel'), ('contrast', 'Kontrast')], default='light', max_length=50)),
                ('gender', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_custom_interface', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('Männlich', 'männlich'), ('Weiblich', 'weiblich'), ('Divers', 'divers')], max_length=50)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('citizenship', models.CharField(blank=True, max_length=50, null=True)),
                ('birthdate', models.DateTimeField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdvancedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pp', models.CharField(choices=[('none', '-'), ('bird', 'Vogel'), ('butterfly', 'Schmetterling'), ('cat', 'Katze'), ('dog', 'Hund'), ('duck', 'Ente'), ('jellyfish', 'Qualle'), ('owl', 'Eule'), ('panda', 'Panda'), ('penguin', 'Pinguin'), ('pig', 'Schwein'), ('rabbit', 'Hase'), ('sheep', 'Schaf'), ('snail', 'Schnecke'), ('snake', 'Schlange'), ('turkey', 'Truthan'), ('turtle', 'Schildkröte')], default='none', max_length=50)),
                ('biographie', models.TextField(blank=True, max_length=200, null=True)),
                ('discord_username', models.CharField(blank=True, max_length=20, null=True)),
                ('discord_public', models.BooleanField(default=False)),
                ('epicgames_username', models.CharField(blank=True, max_length=20, null=True)),
                ('epicgames_public', models.BooleanField(default=False)),
                ('facebook_username', models.CharField(blank=True, max_length=20, null=True)),
                ('facebook_public', models.BooleanField(default=False)),
                ('instagram_username', models.CharField(blank=True, max_length=20, null=True)),
                ('instagram_public', models.BooleanField(default=False)),
                ('linkedin_username', models.CharField(blank=True, max_length=20, null=True)),
                ('linkedin_public', models.BooleanField(default=False)),
                ('pinterest_username', models.CharField(blank=True, max_length=20, null=True)),
                ('pinterest_public', models.BooleanField(default=False)),
                ('playstation_username', models.CharField(blank=True, max_length=20, null=True)),
                ('playstation_public', models.BooleanField(default=False)),
                ('reddit_username', models.CharField(blank=True, max_length=20, null=True)),
                ('reddit_public', models.BooleanField(default=False)),
                ('snapchat_username', models.CharField(blank=True, max_length=20, null=True)),
                ('snapchat_public', models.BooleanField(default=False)),
                ('steam_username', models.CharField(blank=True, max_length=20, null=True)),
                ('steam_public', models.BooleanField(default=False)),
                ('threads_username', models.CharField(blank=True, max_length=20, null=True)),
                ('threads_public', models.BooleanField(default=False)),
                ('tiktok_username', models.CharField(blank=True, max_length=20, null=True)),
                ('tiktok_public', models.BooleanField(default=False)),
                ('twitter_username', models.CharField(blank=True, max_length=20, null=True)),
                ('twitter_public', models.BooleanField(default=False)),
                ('xbox_username', models.CharField(blank=True, max_length=20, null=True)),
                ('xbox_public', models.BooleanField(default=False)),
                ('xing_username', models.CharField(blank=True, max_length=20, null=True)),
                ('xing_public', models.BooleanField(default=False)),
                ('youtube_username', models.CharField(blank=True, max_length=20, null=True)),
                ('youtube_public', models.BooleanField(default=False)),
                ('privacy', models.BooleanField(default=False)),
                ('terms', models.BooleanField(default=False)),
                ('copyright', models.BooleanField(default=False)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='administration.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advanced', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('federal_state', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('street', models.CharField(blank=True, max_length=50, null=True)),
                ('housenumber', models.CharField(blank=True, max_length=50, null=True)),
                ('from_date', models.DateField(default=datetime.date(1, 1, 1))),
                ('to_date', models.DateField(default=datetime.date(1, 1, 1))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
