# Generated by Django 4.2.4 on 2023-09-08 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '__first__'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advanceduser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='advanceduser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='advanceduser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='advanceduser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='advanceduser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='advanceduser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='advanceduser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='advanceduser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='advanceduser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='advanceduser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='advanceduser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='advanceduser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='advanceduser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='advanceduser',
            name='username',
        ),
        migrations.AddField(
            model_name='advanceduser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.role'),
        ),
        migrations.AddField(
            model_name='advanceduser',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='advanced', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
