# Generated by Django 4.2.4 on 2023-09-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officesync',
            name='logo',
            field=models.ImageField(blank=True, default='authentication/static/images/uploads/logo_default/officesync.png', null=True, upload_to='authentication/static/images/uploads/logo'),
        ),
    ]
