# Generated by Django 4.2.4 on 2023-12-25 03:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='to_date',
            field=models.DateField(blank=True, default=datetime.date(1, 1, 1), null=True),
        ),
    ]
