# Generated by Django 3.2.20 on 2023-11-24 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_officesync_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advanceduser',
            name='pp',
            field=models.CharField(choices=[('none', '-'), ('bird', 'Vogel'), ('butterfly', 'Schmetterling'), ('cat', 'Katze'), ('dog', 'Hund'), ('duck', 'Ente'), ('jellyfish', 'Qualle'), ('owl', 'Eule'), ('panda', 'Panda'), ('penguin', 'Pinguin'), ('pig', 'Schwein'), ('rabbit', 'Hase'), ('sheep', 'Schaf'), ('snail', 'Schnecke'), ('snake', 'Schlange'), ('turkey', 'Truthan'), ('turtle', 'Schildkröte')], default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='usercustominterface',
            name='ui',
            field=models.CharField(choices=[('light', 'Hell'), ('dark', 'Dunkel'), ('contrast', 'Kontrast')], default='light', max_length=50),
        ),
        migrations.AlterField(
            model_name='warn',
            name='reason',
            field=models.CharField(choices=[('misinformation', 'Falschinformationen'), ('abuse', 'Missbrauch von Privilegien'), ('harassment', 'Belästigung'), ('bullying', 'Cybermobbing'), ('grooming', 'Cybergrooming'), ('whataboutism', 'Whataboutismus'), ('relativisation', 'Relativierung'), ('blackmailing', 'Erpressung'), ('threat', 'Drohung'), ('cow', 'Wortwahl'), ('hatespeech', 'Hassrede'), ('swearword', 'Beleidigung'), ('discrimination', 'Diskriminierung'), ('Sexism', 'Sexismus'), ('racism', 'Rassismus'), ('fascism', 'Faschismus'), ('antisemitism', 'Antisemitismus'), ('islamophobia', 'Islamophobie'), ('homophobia', 'Homophobie'), ('scam', 'Betrug'), ('spam', 'Spam')], default='hatespeech', max_length=50),
        ),
    ]
