# Generated by Django 4.2.4 on 2023-12-25 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0002_alter_adress_to_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adress',
            options={'ordering': ['-id']},
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergies', models.CharField(blank=True, max_length=50, null=True)),
                ('chronic_diseases', models.CharField(blank=True, max_length=50, null=True)),
                ('medical_treatments', models.CharField(blank=True, max_length=50, null=True)),
                ('medication', models.CharField(blank=True, max_length=50, null=True)),
                ('mental_health', models.CharField(blank=True, max_length=50, null=True)),
                ('vaccines', models.TextField(blank=True, max_length=500, null=True)),
                ('others', models.TextField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
