# Generated by Django 4.2.4 on 2023-08-19 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_userinterface_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCustomInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_interface', to='authentication.user')),
            ],
        ),
        migrations.DeleteModel(
            name='UserInterface',
        ),
    ]
