# Generated by Django 4.2.4 on 2023-08-19 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_usercustominterface_delete_userinterface'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCustomInterface',
        ),
    ]
