# Generated by Django 3.2.20 on 2023-12-27 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_absence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='confirmation',
            field=models.CharField(choices=[('Angenommen', 'approved'), ('Abgelehnt', 'rejected')], max_length=50),
        ),
    ]
