# Generated by Django 4.2.4 on 2023-08-19 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0007_advanceduser_alter_warn_user_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warn',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warns', to=settings.AUTH_USER_MODEL),
        ),
    ]
