# Generated by Django 3.2.20 on 2023-12-27 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0007_alter_absence_confirmation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permonance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('appearance', models.TextField(max_length=200)),
                ('teamwork', models.TextField(max_length=200)),
                ('helpfulness', models.TextField(max_length=200)),
                ('politeness', models.TextField(max_length=200)),
                ('communication', models.TextField(max_length=200)),
                ('work_quality', models.TextField(max_length=200)),
                ('work_organisation', models.TextField(max_length=200)),
                ('knowledge', models.TextField(max_length=200)),
                ('goals', models.TextField(max_length=200)),
                ('grade', models.FloatField()),
                ('evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
