# Generated by Django 4.2.4 on 2023-08-19 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0008_alter_warn_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCustomInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('Hell', 'Hell'), ('Dunkel', 'Dunkel'), ('Kontrast', 'Kontrast')], default='Hell', max_length=50)),
                ('gender', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_custom_interface', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
