# Generated by Django 4.2.4 on 2023-08-19 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_usercustominterface'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercustominterface',
            old_name='reason',
            new_name='ui',
        ),
    ]
