# Generated by Django 3.2.20 on 2023-12-27 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0009_alter_permonance_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permonance',
            name='evaluator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_performances', to=settings.AUTH_USER_MODEL),
        ),
    ]
