# Generated by Django 3.2.20 on 2023-12-27 02:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0010_alter_permonance_evaluator'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Permonance',
            new_name='Performance',
        ),
    ]
