# Generated by Django 4.2.4 on 2023-08-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_rename_reason_usercustominterface_ui'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(blank=True, default='OfficeSync', max_length=20, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='static/images/uploads/logo')),
            ],
        ),
    ]
