# Generated by Django 3.2.20 on 2023-12-28 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_reprimant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advanceduser',
            name='discord_public',
        ),
        migrations.RemoveField(
            model_name='advanceduser',
            name='epicgames_public',
        ),
        migrations.RemoveField(
            model_name='advanceduser',
            name='facebook_public',
        ),
        migrations.RemoveField(
            model_name='advanceduser',
            name='instagram_public',
        ),
        migrations.RemoveField(
            model_name='advanceduser',
            name='linkedin_public',
        ),
        migrations.RemoveField(
            model_name='advanceduser',
            name='pinterest_public',
        ),
        migrations.RemoveField(
            model_name='advanceduser',
            name='playstation_public',
        ),
        migrations.RemoveField(
            model_name='advanceduser',
            name='reddit_public',
        ),
        migrations.RemoveField(
            model_name='advanceduser',
            name='snapchat_public',
        ),
        migrations.RemoveField(
            model_name='advanceduser',
            name='steam_public',
        ),
        migrations.RemoveField(
            model_name='advanceduser',
            name='threads_public',
        ),
        migrations.RemoveField(
            model_name='advanceduser',
            name='tiktok_public',
        ),
        migrations.RemoveField(
            model_name='advanceduser',
            name='twitter_public',
        ),
        migrations.RemoveField(
            model_name='advanceduser',
            name='xbox_public',
        ),
        migrations.RemoveField(
            model_name='advanceduser',
            name='xing_public',
        ),
        migrations.RemoveField(
            model_name='advanceduser',
            name='youtube_public',
        ),
    ]
