# Generated by Django 3.2.20 on 2023-12-28 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_auto_20231228_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advanceduser',
            name='biographie',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
