# Generated by Django 3.2.20 on 2023-11-23 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('gray', 'Grau'), ('red', 'Rot'), ('orange', 'Orange'), ('yellow', 'Gelb'), ('green', 'Grün'), ('cyan', 'Türkis'), ('blue', 'Blau'), ('purple', 'Violett')], default='gray', max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
